### ISSUE TITLE
Remove Sign Up and Log On from all title bar

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/Thunderbots5604.github.io#10]
It is near impossible to implement this on user side. We should remove them.

**Comment by danielgrimshaw** [comment]
@javieranton1999 @Thunderbots5604/owners

**Comment by ghost** [comment]
Yeah, I have been considering this for a while. But, as of right now the navigation bar seems empty without it, and I'm going to leave it there for the lack of something better to put.

**Comment by ZachOhara** [comment]
You could replace it with a link to the github organization page.

**Comment by zachw000** [comment]
The server side verification could be done on another remote server if you want to keep the Login/Sign Up section. And as for dynamic loading for each account this can be done with AngularJS and AJAX/jQuery

**Comment by knightsean00** [comment]
I think it would be worth it for someone to take a look at this 
https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template

**Comment by ghost** [comment]
That is just for the layout of the sign up/log on buttons @knightsean00

**Comment by knightsean00** [comment]
@javieranton1999 
Check out the right side of the page, it continues on, there is a total of 119 pages.
