### ISSUE TITLE
Slightly narrowed window creates unnecessary space

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots5604/Thunderbots5604.github.io#14]
Slightly narrowing the browser window causes the buttons to realign (which they should), but it creates unnecessary space between the buttons. It would be appropriate for the buttons to expand lengthwise to fill all the available space. A screenshot is shown below. The buttons should expand in _all_ page widths, not just the pictured width.

![website](https://cloud.githubusercontent.com/assets/7062009/9977342/5f0f2e38-5eb8-11e5-8a4c-f0e448343131.png)

**Comment by knightsean00** [comment]
Outdated and irrelevant

**Comment by ZachOhara** [comment]
Nope, this is still an issue.
![image](https://cloud.githubusercontent.com/assets/7062009/11802062/037ab7fe-a2a1-11e5-95bb-45232e46e034.png)

**Comment by knightsean00** [comment]
This is a problem with the CSS Javier chose for alignment

**Comment by knightsean00** [comment]
Again, a bootstrap problem.

**Comment by ZachOhara** [comment]
That doesn't mean we can't mitigate it or fix it
