### ISSUE TITLE
Sign Up Section Implementation

### ISSUE THREAD

**Issue by zachw000** [Thunderbots5604/Thunderbots5604.github.io#2]
@javieranton1999 I noticed you did not implement a sign in section, I was thinking though not the best solution to make the sign-in process with javascript, simply because of GitHub's lack of server scripting, and we could also store all of the user credentials in a JSON file which can be loaded dynamically using AJAX, AngularJS or something of the sorts. Please provide me any feedback on the details of how you plan to implement this feature. (if at all)

**Comment by ghost** [comment]
@zachw000 
Hey Zach! I was originally planning on implementing the sign-in process with php, but if GitHub doesn't fully support server-side programs, I'll probably have to do it in an Angular application.

**Comment by zachw000** [comment]
@javieranton1999 
That is correct, GitHub doesn't support server-side languages, so we can use an angular application, and if you want I could give you some sample code to work off of.

**Comment by ZachOhara** [comment]
This issue is closed. We decided to not use any account system for the website, and all functionality related to the 'sign up' and 'log in' buttons has been removed.
