### ISSUE TITLE
Top hover-buttons have uneven vertical spacing

### ISSUE THREAD

**Issue by PranavMathur** [Thunderbots5604/Thunderbots5604.github.io#20]
![image](https://cloud.githubusercontent.com/assets/7075088/10852348/844678be-7eed-11e5-812e-deb9b6ede1b7.png)

**Comment by knightsean00** [comment]
It's even.

**Comment by danielgrimshaw** [comment]
Move the text lower so it is even with the titlebar.

**Comment by JakeOhara** [comment]
@knightsean00 The hover buttons aren't even on chrome; what browser are you using?

**Comment by knightsean00** [comment]
Opera

**Comment by knightsean00** [comment]
I can't see any problem, seriously.

**Comment by PranavMathur** [comment]
Recreating the problem on Opera:

![image](https://cloud.githubusercontent.com/assets/7075088/10864620/4477949c-7fb1-11e5-821e-0e3f1aa71391.png)
