### ISSUE TITLE
Images in outreach page are not always properly aligned

### ISSUE THREAD

**Issue by PranavMathur** [Thunderbots5604/Thunderbots5604.github.io#23]
![image](https://cloud.githubusercontent.com/assets/7075088/11322235/17ea2736-9097-11e5-8925-9886f1a7cc30.png)

**Comment by PranavMathur** [comment]
@knightsean00 
@JakeOhara 
@javieranton1999

**Comment by knightsean00** [comment]
Pranav, this was a 6 md column in boot strap, then the images were centered vertically, so vertical alignment is not the problem, what is?

**Comment by knightsean00** [comment]
Fixed in latest commit
