### ISSUE TITLE
Sorting Team members by Alphabetical or Chronological order

### ISSUE THREAD

**Issue by PranavMathur** [Thunderbots5604/Thunderbots5604.github.io#24]
Is it possible for their to be a toggle of sorts? Like this: 
![image](https://cloud.githubusercontent.com/assets/7075088/11331081/900046be-916a-11e5-81e8-1bb94b0310e7.png)

**Comment by PranavMathur** [comment]
Is this possible?

**Comment by ZachOhara** [comment]
Team members should not be sorted by join date.
