### ISSUE TITLE
Gallery takes far longer to load than it should 

### ISSUE THREAD

**Issue by JakeOhara** [Thunderbots5604/Thunderbots5604.github.io#25]
Images should be compressed, and possibly gallery changed to load at a reasonable time (currently 8-9 seconds on a good internet connection). Side note, it would be nice to have a gallery that fit the flat theme of the website more.

**Comment by knightsean00** [comment]
It's already been compressed to be half of what it usually is.

**Comment by knightsean00** [comment]
Bruh, the images are compressed as much as possible, unless you wanna do a
middle out compression

**Comment by JakeOhara** [comment]
Reopened; issue is not resolved. 
Compressing images is a good start, and when preformed it greatly reduced load time (was orignally ~15 seconds). The gallery is suuuuper slow to load though, and that's a problem within the actual gallery code. We should find a better template tbh.
