### ISSUE TITLE
New gallery not loading properly on mobile

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/Thunderbots5604.github.io#27]
1) The grey boxes should be a uniform size to make the display more grid-like (or there should be more white space to make it a grid, it just needs to be a grid): 
![image](https://cloud.githubusercontent.com/assets/8226905/12162334/6ad55032-b4b5-11e5-8ee1-49ae3688beee.png)

2) The text needs to scale with the pictures, right now it dwarfs them in some cases: 
![image](https://cloud.githubusercontent.com/assets/8226905/12162350/a56fdb90-b4b5-11e5-8f38-daa32095021e.png)

**Comment by knightsean00** [comment]
The tiles not being aligned is purposeful, however, the programmers part is a problem with the default viewport size, this will be remedied tomorrow, because I am tired, but my plan is to change the minimum size of the website for mobile, and switch the img on the nav to center so it looks correct.

**Comment by knightsean00** [comment]
This has been fixed in the latest commit
