### ISSUE TITLE
The font is not consistent on trc.html

### ISSUE THREAD

**Issue by knightsean00** [Thunderbots5604/Thunderbots5604.github.io#29]
![2016-01-25 21_45_19-action center](https://cloud.githubusercontent.com/assets/13596473/12573378/0f73951c-c3ad-11e5-9939-89a8a36e86a2.png)

**Comment by PranavMathur** [comment]
7b2fe1d does not fix this issue.

![image](https://cloud.githubusercontent.com/assets/7075088/12773725/292d7bd4-c9f3-11e5-9e38-7113e2d01fe0.png)

**Comment by knightsean00** [comment]
Is it necessary to have bullets, because you can just add that in as UTF8 Character.

Also, something is weird with your code, there shouldn't be any bullets on the li tag because I have set all the ul and li tags to not have any style to it. This is was in the overall wrapper tag in main.css
