### ISSUE TITLE
Custom domain hosting

### ISSUE THREAD

**Issue by jinkokaki** [Thunderbots5604/Thunderbots5604.github.io#30]
Should we buy a custom domain (ex. thunderbots5604.org) for $12/year from Google?
[Link](https://domains.google.com/m/registrar/search?searchTerm=thunderbots5604&hl=en&_ga=2.65198955.475769363.1559346080-1153537042.1559346080)

**Comment by jinkokaki** [comment]
Purchased domain thunderbots5604.org, configuring DNS and then it should work

**Comment by christiankaneen** [comment]
Thank you for setting it up!

Thanks,
Christian Kaneen
christian.kaneen@evergreenps.org
Gateway To Technology
FIRST Robotics Advisor
Covington Middle School
(360) 604-6300 ext. 5863

________________________________
