### ISSUE TITLE
On team.html hovering over content buttons makes text hard to read

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/Thunderbots5604.github.io#6]
All you need to change is the text color in the hover pseudoclass.

**Comment by danielgrimshaw** [comment]
@javieranton1999 @Thunderbots5604/owners

**Comment by ghost** [comment]
I put the background transition to better show that it's a clickable pill. It's clearly readable before hovering, although hovering does make it a little harder to read. I'll mess around with the colors to fix this.

**Comment by ZachOhara** [comment]
Reopened: the issue is not resolved.

Also, I'll add that the text before hovering is a little hard to see, and could be improved.

**Comment by knightsean00** [comment]
Issue Closed.

**Comment by knightsean00** [comment]
The color scheme was changed, everything is of the all right variety
