### ISSUE TITLE
Error page takes user to home page, regardless of initial location

### ISSUE THREAD

**Issue by PranavMathur** [Thunderbots5604/Thunderbots5604.github.io#7]
@javieranton1999 This could be fixed by having a subpage of each location, such as /team/error and /sponsors/error

**Comment by ghost** [comment]
The error page is a temporary installment, and I don't plan to have it at all in the website for much longer.

**Comment by ZachOhara** [comment]
Reopened: Issue is not resolved

**Comment by knightsean00** [comment]
Outdated because there is no reason to have an error page
