### ISSUE TITLE
Remove Watermark at bottom of pages

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/Thunderbots5604.github.io#8]
@javieranton1999 please remove your watermark at the bottom of the page. It makes it look like we payed you off to do it. @Thunderbots5604/owners

**Comment by ghost** [comment]
That section of the footer at the bottom is more or less of a placeholder, until I get something else to put there.

**Comment by ZachOhara** [comment]
Reopened: the issue is not resolved.

You can close the issue when the placeholder is gone.

**Comment by knightsean00** [comment]
Issue has been fixed as far as I know
