### ISSUE TITLE
Hovering over the social media icons causes the icon to flicker

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots5604/Thunderbots5604.github.io#9]
The first time visiting the website on any computer, hovering over the social media icons at the bottom of the page causes the icon to flicker. This happens once and only once, and will not happen again even after reloading the page or restarting the browser.

Credit to @PranavMathur for discovering this.

@Thunderbots5604/owners

**Comment by ZachOhara** [comment]
UPDATE: The flicker is reproducible by clearing the web browser's cache, then revisiting the page.

**Comment by ghost** [comment]
This has been a known issue for a while, and I believe it's actually a bug in webkit which can't properly transition between background images of divs. I've removed the feature for now, but I'll try to find a way to get the transition to work without flickering in the meantime.

**Comment by knightsean00** [comment]
Issue has been fixed

Close Issue.
